include ../Makefile.env

TARGET = query_vk_devices

SRCS = 
SRCS += main.c

OBJS =
OBJS += $(patsubst %.cc,%.o,$(patsubst %.cpp,%.o,$(patsubst %.c,%.o,$(SRCS))))

INCLUDES +=

CFLAGS   +=

LDFLAGS  +=

include ../Makefile.include
